UseProxy: false
HttpProxy: http://127.0.0.1:10809
EveryTime: 6h
SubTypePriority: 1
SubNameFormatter: 1
SaveMultiSub: true
Threads: 2
RunAtStartup: true
MovieFolder: /media/movies
SeriesFolder: /media/tv
